load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "get_route",
    srcs = [ "get_route.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "async_get_route",
    srcs = [ "async_get_route.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "benchmark",
    srcs = [ "benchmark.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "echo_consumer",
    srcs = [ "echo_consumer.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "echo_locality_aware",
    srcs = [ "echo_locality_aware.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "get_all_instances",
    srcs = [ "get_all_instances.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "get_route_with_set",
    srcs = [ "get_route_with_set.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "get_route_go_cst",
    srcs = [ "get_route_go_cst.cpp" ],
    deps = [ "//:polaris_api" ],
)

cc_binary(
    name = "register_load_balancer",
    srcs = [ "register_load_balancer.cpp" ],
    deps = [ "//:polaris_api" ],
)
